modname="LTN_Status_on_logistic_network"
signal_dispatcher_no_train_found="ltn-".."dispatcher-no-train-found"
signal_provider_missing_cargo="ltn-".."provider-missing-cargo"
signal_provider_unscheduled_cargo="ltn-".."provider-unscheduled-cargo"
signal_requester_unscheduled_cargo="ltn-".."requester-unscheduled-cargo"